import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { CpuIcon, FilePenIcon, PenIcon } from "lucide-react"
import Link from "next/link"

export default function Component() {
  return (
    <div className="flex flex-col min-h-dvh">
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6 grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
          <div className="flex flex-col justify-center space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                Unleash the Power of AI-Generated Content
              </h1>
              <p className="max-w-[600px] text-muted-foreground md:text-xl">
                Discover how our advanced AI technology can create engaging, informative content tailored to your needs.
                Unlock new possibilities for your business or personal projects.
              </p>
            </div>
          </div>
          <img
            src="/logo.svg"
            alt="AI Content Generation"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
            width="300"
            height="300"
          />
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6 space-y-12">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">How it Works</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our AI-powered content generation process is designed to deliver high-quality, tailored results. Let's
                break it down step-by-step.
              </p>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-start gap-12 lg:grid-cols-3">
            <div className="grid gap-4">
              <div className="bg-primary rounded-md p-4 flex items-center justify-center">
                <PenIcon className="w-8 h-8 text-primary-foreground" />
              </div>
              <h3 className="text-xl font-bold">Prompt Engineering</h3>
              <p className="text-muted-foreground">
                Our team of experts crafts detailed prompts that capture your specific requirements, ensuring the AI
                generates content tailored to your needs.
              </p>
            </div>
            <div className="grid gap-4">
              <div className="bg-secondary rounded-md p-4 flex items-center justify-center">
                <CpuIcon className="w-8 h-8 text-secondary-foreground" />
              </div>
              <h3 className="text-xl font-bold">AI Content Generation</h3>
              <p className="text-muted-foreground">
                Our advanced AI models analyze the prompt and leverage their vast knowledge to produce high-quality,
                original content in a matter of seconds.
              </p>
            </div>
            <div className="grid gap-4">
              <div className="bg-muted rounded-md p-4 flex items-center justify-center">
                <FilePenIcon className="w-8 h-8 text-muted-foreground" />
              </div>
              <h3 className="text-xl font-bold">Review and Refine</h3>
              <p className="text-muted-foreground">
                Our team reviews the generated content, providing feedback and making any necessary adjustments to
                ensure it meets your standards and expectations.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
        <div className="container px-4 md:px-6 space-y-12">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Example Outputs</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Check out some sample content generated by our AI to get a sense of the quality and versatility of our
                offerings.
              </p>
            </div>
          </div>
          <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
            <Card className="h-full w-full">
              <CardHeader>
                <CardTitle>Blog Post</CardTitle>
                <CardDescription>A 500-word blog post on the benefits of AI-generated content.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  "Artificial intelligence has revolutionized the way we \n approach content creation. By leveraging the
                  power of \n advanced language models, businesses and individuals can \n now generate high-quality,
                  engaging content at a fraction \n of the time and cost..."
                </p>
              </CardContent>
            </Card>
            <Card className="h-full w-full">
              <CardHeader>
                <CardTitle>Product Description</CardTitle>
                <CardDescription>A detailed product description for a new smart home device.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  "Introducing the Acme Smart Home Hub, the ultimate \n solution for seamless home automation. Powered
                  by \n cutting-edge AI technology, this compact device \n integrates with a wide range of smart home
                  devices..."
                </p>
              </CardContent>
            </Card>
            <Card className="h-full w-full">
              <CardHeader>
                <CardTitle>Social Media Post</CardTitle>
                <CardDescription>A captivating social media post for a new product launch.</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  "Attention, tech enthusiasts! We're thrilled to announce \n the launch of our latest innovation, the
                  Acme Smartwatch. \n Designed to revolutionize the way you track your fitness \n and stay connected..."
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6 space-y-12">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Ready to Elevate Your Content?</h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our AI-powered content generation service is here to help you create engaging, high-quality content with
                ease. Get started today and unlock new possibilities for your business or personal projects.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Link
                href="/dashboard/Contact"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}style={{ cursor: 'url(/poin.png), auto' }}
              >
                Contact Us
              </Link>
              <Link
                href="/dashboard/Pricing"
                className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                prefetch={false}style={{ cursor: 'url(/poin.png), auto' }}
              >
                View Pricing
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
